
my:
  name: Hill
  greeting: =====  hello all the word, i am ${my.name} ========
  listOfValues: one,two,three

carInfo: "{name: 'golf', year : '2004', fuel: 'diesel'}"

server.port: 8084


db:
  connection : "{connectionString: 'http//:localhost:494' , userName: 'foo', password:  'foo'}"
  host: 127.3.0.2
  port: 8085




# we ask spring actuator to display all the configuration existing in the properties file, to see all of it one the web type "localhost:8084/actuator/configprops"
management.endpoints.web.exposure.include : "*"

# to use the remote confjg server located on remote git repo
spring:
  cloud:
    config:
      uri: "http://localhost:8888"

#    to specify which yml file, if this does not exist , it will automatically goes to application.yml
  application:
             name: microservice-config-one
#      once the spring.cloud.config.uri exist, it automatically override the profiles
  profiles:
          active: test





# this here is to activate the test profile "application-test"
#spring:
#      profiles:
#               active: test


